### ISSUE TITLE
Prevent people from getting on top of the map

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/DeeperWorld#52]
In some sections the width dont match up and the player wont be tped. Seems we got some prevention when descending as it bumps you or whatever (should also come with a text explaining it as its not really clear for alot of people).

When the section above is smaller however, it just lets the player run ontop of the map allowing for easy access to:
1: fast travel layers
2: go outside the map some spots in l3 (are ways around Offz's damage system as found by BoatMeat)

**Comment by 0ffz** [comment]
We can improve the damage system thanks to norazan's vehicle tree thing, should prolly move that into idofront and use it here in deeperworld.

As for preventing going up, the issue is that although it tries to bounce you back, it's often not enough. I could probably cancel the move event entirely while going upwards but im sure you could glitch through it still. Perhaps it's a better idea though and will at least make it harder to get up there.
